### ISSUE TITLE
请教下专家 MapBox加载其他坐标系底图问题

### ISSUE THREAD

**Issue by hy31337** [cdhuangyong/TileXYZLayerFor4326#1]
您好，我现在用的MapBox加载的WGS1984无偏移坐标系（4326），数据都是在这个上面加工的，然后切换底图到WGS 1984 Web-Mercator（3857），发现底图有点点偏移，请问下我能设置这个图层（3857）偏移 或用什么插件能够解决吗？

**Comment by hy31337** [comment]
专家，我试了你这里提供的 好多种方法，都没有把这两个底图在MapBox中实现无偏移叠加，请问有什么好的办法实现吗？
（WGS84）
http://t0.tianditu.com/vec_w/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=vec&STYLE=default&TILEMATRIXSET=w&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&FORMAT=tiles=&tk=
（GCJ02）		
https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}

**Comment by cdhuangyong** [comment]
抱歉才看到这个消息，我还是解答一下：这个layer只适用于标准的4326坐标系的瓦片接入，技术上用的类似重投影原理，3857还是用mapbox本身的raster图层接入吧，还有如果你的3857坐标有偏移，可以从几个方面排查：1、这个图层的做法重投影并不是精度那么高，如果你要基于这个4326的底图生产数据请慎重，2、层级分辨率，这个可以参考openlayers的原理，3、你叠加的数据和瓦片本身是否对应了，比如你的数据是高德坐标系的，而底图是WGS84的，就会有一点偏移

**Comment by hy31337** [comment]
谢谢，直接使用openlayers 解决了

**Comment by hy31337** [comment]
谢谢，直接使用openlayers并做偏移处理解决了
